title: "Adventures in Digital Art History"
author: K. Kleutghen
email: [my surname] [at] wustl [dot] edu
description: > # this means to ignore newlines until "baseurl:"
  Endeavors, experiments, errors, and explorations in post-analog Art History

theme: minima

# social links
github_organization_username: Project-Kleutghen
github_username:  kkleutghen

show_excerpts: true # set to false to remove excerpts on the homepage
